// MDFS-EXAMS/EXAM_MDFS2-2/examenpracticoangular/src/routes/menu/menu.component.ts
import { Serie } from './../../app/models/Serie';
import { SeriesService } from './../../app/services/series.service';
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css']
})
export class MenuComponent implements OnInit {

  @ViewChild("serie") serie:ElementRef;
  public series:Array<Serie>;
  constructor(private _service:SeriesService, private _router:Router) { }

  verSerie(){
    let s = this.serie.nativeElement.value;
    console.log(s);
    this._router.navigate(['serie',s]);
  }
  ngOnInit(): void {
    this._service.getSeries().subscribe((res)=>{
      this.series=res;
      console.log(this.series)
    },error=>{
      console.log(error);
    });
  }

}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <select (change)="verSerie()" #serie name="serie" class="nav-link dropdown-toggle">
          <option class="dropdown-menu">Series</option>
          <option *ngFor="let serie of series" value="{{serie.idSerie}}">{{serie.nombre}}</option>
      </select>
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/modificar">Modificar Personaje</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/insertar">Insertar Personaje</a>
        </li>
        <li class="nav-item dropdown">
       
        </li>
      </ul>
    </div>
  </nav>

// Tajamar-MDFS/MDFS-3/09_react_appempleados/src/routes/Menu.js
import React, { Component } from "react";
import {NavLink} from 'react';

export default class Menu extends Component {
  render() {
    return (
      <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
        <a className="navbar-brand" href="/">Empresa</a>
        <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span className="navbar-toggler-icon"></span>
        </button>

        <div className="collapse navbar-collapse" id="navbarSupportedContent">
          <ul className="navbar-nav mr-auto">
            <li className="nav-item active">
              <a className="nav-link" href="/">Departamentos <span className="sr-only">(current)</span></a>
            </li>
            <li className="nav-item">
              <a className="nav-link" href="/insert">Crear</a>
            </li>
            <li className="nav-item dropdown">
              <a className="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Disabled
              </a>
              <div className="dropdown-menu" aria-labelledby="navbarDropdown">
                <a className="dropdown-item" href="#">Action</a>
                <a className="dropdown-item" href="#">Another action</a>
                <div className="dropdown-divider"></div>
                <a className="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li className="nav-item">
              <a className="nav-link disabled" href="#">Disabled</a>
            </li>
          </ul>
        </div>
      </nav>
    );
  }
}
